root: true

env:
  browser: true
  node: true
  es2023: true

extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:prettier/recommended

plugins:
  - @typescript-eslint

parserOptions:
  ecmaVersion: latest
  sourceType: module

rules:
  # TypeScript
  @typescript-eslint/no-unused-vars:
    - error
    - argsIgnorePattern: "^_"

  @typescript-eslint/no-explicit-any: warn

  # Next.js / React
  react/react-in-jsx-scope: off
  @next/next/no-html-link-for-pages: off

  # Server-side safety
  no-console:
    - warn
    - allow: ["warn", "error"]
